cuts :
    npart_dm : 1000 1e60
    npart_baryon : 300 1e60
    x : 0. 100000.
    y : 0. 100000.
    z : 0. 100000.

include :
    halo_matching : True

snapshot : 85

baryon_shapes : /physics2/ssamurof/massive_black_ii/subhalo_cat-nthreshold5-proj+3d.fits
dm_shapes : /physics2/ssamurof/massive_black_ii/subhalo_cat-nthreshold5-proj+3d.fits
output : /physics2/ssamurof/massive_black_ii/cats/base_subhalo_shapes-v6-ndm1000-nst300.fits

symmetrisation:
    catalogue : /physics2/ssamurof/massive_black_ii/cats/base_subhalo_shapes-v6-ndm1000-nst300.fits
    output : /physics2/ssamurof/massive_black_ii/cats/base_subhalo_shapes-v6-ndm1000-nst300-symmetrised.fits

errors:
    nsub : 3


2pt:
    ctypes : ed gg
    errors: True
    shapes : /physics2/ssamurof/massive_black_ii/cats/base_subhalo_shapes-v6-ndm1000-nst300-symmetrised.fits
    savedir: /physics2/ssamurof/massive_black_ii/2pt/ns300_nd1000/v6/symmetrised
    split : most_massive
    split_val : 1
    binning : log
    rmin : 0.1
    rmax : 50.
    nbin : 6