
random_seed : 99000
root_folder : '/physics/yfeng1/mb2'
simulation : massiveblackii

catalogues:
    snapshot : 68
    shapes_method : inertia_tensor 
    postprocessed : /physics2/ssamurof/massive_black_ii/cats/final2/postprocessed/base_subhalo_shapes-v10-ndm1000-nst300-snapshot68.fits
    shapes_dir : /physics2/ssamurof/massive_black_ii/cats/final2/raw/

    cuts :
        npart_dm : 1000 1e60
        npart_baryon : 300 1e60
        x : 0. 100000.
        y : 0. 100000.
        z : 0. 100000.

    halo_matching : True

symmetrisation:
    catalogue : /physics2/ssamurof/massive_black_ii/cats/final2/postprocessed/base_subhalo_shapes-v10-ndm1000-nst300-snapshot68.fits
    output : /physics2/ssamurof/massive_black_ii/cats/final2/postprocessed/base_subhalo_shapes-v10-ndm1000-nst300-snapshot68-symmetrised.fits
    pivot_type : mass
    central_type : spatial_central


errors:
    nsub : 3

2pt:
    mode: errors
    ctypes : ed ee gi_plus_projected ii_plus_projected
    errors: True
    shapes : /Users/hattifattener/Documents/ias/mbii/cats/final2/postprocessed/base_subhalo_shapes-v10-ndm1000-nst300-snapshot68.fits
    shapes_symmetrised : /Users/hattifattener/Documents/ias/mbii/cats/final2/postprocessed/base_subhalo_shapes-v10-ndm1000-nst300-snapshot68-symmetrised0.fits
    savedir: /Users/hattifattener/Documents/ias/mbii/2pt/ns300_nd1000/v10/snapshot68
    split : 
    split_val : 1
    binning : log
    rmin : 0.1
    rmax : 33.
    nbin : 6
    rpmin : 0.1
    rpmax : 33.
    nrpbin : 6
    pi_max : 33.

