
random_seed : 99000
root_folder : '/physics/yfeng1/mb2'
simulation : massiveblackii

catalogues:
    snapshot : 85
    shapes_method : inertia_tensor 
    postprocessed : /physics2/ssamurof/massive_black_ii/cats/final2/postprocessed/base_subhalo_shapes-v10-ndm300-nst300-snapshot85-final.fits
    shapes_dir : /physics2/ssamurof/massive_black_ii/cats/final2/raw

    cuts :
        npart_dm : 300 1e60
        npart_baryon : 300 1e60
        x : 0. 100000.
        y : 0. 100000.
        z : 0. 100000.

    halo_matching : True

symmetrisation:
    catalogue : /physics2/ssamurof/massive_black_ii/cats/final/postprocessed/base_subhalo_shapes-v10-ndm1000-nst300-snapshot85-final.fits
    output : /physics2/ssamurof/massive_black_ii/cats/final/postprocessed/base_subhalo_shapes-v10-ndm1000-nst300-snapshot85-final-symmetrised.fits
    pivot_type : mass
    central_type : spatial_central


errors:
    nsub : 3

2pt:
    ctypes : ed ee gg giplus_proj giplus_3d 
    errors: True
    shapes : /physics2/ssamurof/massive_black_ii/cats/final/postprocessed/base_subhalo_shapes-v10-ndm1000-nst300-snapshot85-symmetrised0.fits
    savedir: /physics2/ssamurof/massive_black_ii//2pt/ns300_nd1000/v10/
    split : most_massive
    split_val : 1
    binning : log
    rmin : 0.1
    rmax : 33.
    nbin : 6
    rpmin : 0.1
    rpmax : 30.
    nrpbin : 6
    pi_max : 0.2

