
random_seed : 99000
root_folder : '/nfs/nas-0-1/vat/Illustris-1'
simulation : illustris

catalogues:
    snapshot : 135
    shapes_method : inertia_tensor 
    postprocessed : /physics2/ssamurof/massive_black_ii/cats/final2/postprocessed/illustris-base_subhalo_shapes-v10-ndm1000-nst300-snapshot135.fits
    shapes_dir : /physics2/ssamurof/massive_black_ii/cats/final2/raw

    cuts :
        npart_dm : 1413 1e60
        npart_baryon : 724 1e60
        x : 0. 75000.
        y : 0. 75000.
        z : 0. 75000.

    halo_matching : True

symmetrisation:
    catalogue : /physics2/ssamurof/massive_black_ii/cats/final2/postprocessed/illustris-base_subhalo_shapes-v10-ndm1000-nst300-snapshot135.fits
    output : /physics2/ssamurof/massive_black_ii/cats/final2/postprocessed/illustris-base_subhalo_shapes-v10-ndm1000-nst300-snapshot135-symmetrised.fits
    pivot_type : mass
    central_type : spatial_central


errors:
    nsub : 3

2pt:
    ctypes : gg ed ee giplus_proj iiplus_proj
    mode: 2pt
    errors: True
    shapes : /Users/hattifattener/Documents/ias/mbii/cats/final2/postprocessed/illustris-base_subhalo_shapes-v10-ndm1000-nst300-snapshot135-symmetrised0.fits
    savedir: /Users/hattifattener/Documents/ias/mbii/2pt/ns300_nd1000/v10/illustris/symmetrised/
    split : spatial_central
    split_val : 1
    binning : log
    rmin : 0.1
    rmax : 22.
    nbin : 6
    rpmin : 0.1
    rpmax : 22.
    nrpbin : 6
    pi_max : 22.

